export default {
  FETCH_TICKETS_REQUEST: 'fetch_tickets_request',
  FETCH_TICKETS_SUCCESS: 'fetch_tickets_success',
  FETCH_TICKETS_FAILURE: 'fetch_tickets_failure',
  FIND_TICKET_BY_ID_REQUEST: 'find_ticket_by_id_request',
  FIND_TICKET_BY_ID_SUCCESS: 'find_ticket_by_id_success',
  FIND_TICKET_BY_ID_FAILURE: 'find_ticket_by_id_failure',
  DELETE_TICKET_REQUEST: 'delete_ticket_request',
  DELETE_TICKET_SUCCESS: 'delete_ticket_success',
  DELETE_TICKET_FAILURE: 'delete_ticket_failure',
  DELETE_MESSAGE_REQUEST: 'delete_message_request',
  DELETE_MESSAGE_SUCCESS: 'delete_message_success',
  DELETE_MESSAGE_FAILURE: 'delete_message_failure',
  CREATE_MESSAGE_REQUEST: 'create_message_request',
  CREATE_MESSAGE_SUCCESS: 'create_message_success',
  CREATE_MESSAGE_FAILURE: 'create_message_failure',
  GET_MESSAGES_REQUEST: 'get_messages_request',
  GET_MESSAGES_SUCCESS: 'get_messages_success',
  GET_MESSAGES_FAILURE: 'get_messages_failure'
}
